### ISSUE TITLE
tariff-create

### ISSUE THREAD

**Issue by Zoomish** [NovaDevelopersCo/NovaLearn-BackEnd#23]
Создать модуль и прописать все запросы по модели для тарифа. Реализовать Get, Post, Put, Delete запросы. Должно быть реализованы по типу пользователей, т.е. запросы через айди. Так же привязать тариф к пользователю (может быть один)

**Comment by merdernoty** [comment]
Какие могут быть тарифы? 

> Создать модуль и прописать все запросы по модели для тарифа. Реализовать Get, Post, Put, Delete запросы. Должно быть реализованы по типу пользователей, т.е. запросы через айди. Так же привязать тариф к пользователю (может быть один)

**Comment by Zoomish** [comment]
> @Zoomish Какие могут быть тарифы? И какой тариф должен быть базовый, должен ли тариф создаваться с пользывателем?
>  
> 
> > Создать модуль и прописать все запросы по модели для тарифа. Реализовать Get, Post, Put, Delete запросы. Должно быть реализованы по типу пользователей, т.е. запросы через айди. Так же привязать тариф к пользователю (может быть один)
> 
> 

Basic - создаётся по дефолту (1 уровень доступа)
Extend (2 уровень доступа)
Pro (третий уровень доступа)
