### ISSUE TITLE
profile tags

### ISSUE THREAD

**Issue by Zoomish** [NovaDevelopersCo/NovaLearn-BackEnd#34]
В пользователя добавить поле tags (массив с тегами как в дискорде)(см. Дерево зависимостей). Так же организовать модуль с моделью тега и всеми запросами к нему. Зависимость many to many(т.е. много пользователей могут меть много тегов). Теги будут кастомные, поэтому сделай пока тестовые

**Comment by merdernoty** [comment]
Сыллку не нашел в дс скинь сюда, должен ли быть базовый тег?(если да то какой), нужен ли тегам левл аксес какой нибудь?(как в ролях и тарифах)


> В пользователя добавить поле tags (массив с тегами как в дискорде)(см. Дерево зависимостей). Так же организовать модуль с моделью тега и всеми запросами к нему. Зависимость many to many(т.е. много пользователей могут меть много тегов). Теги будут кастомные, поэтому сделай пока тестовые

**Comment by Zoomish** [comment]
> Сыллку не нашел в дс скинь сюда, должен ли быть базовый тег?(если да то какой), нужен ли тегам левл аксес какой нибудь?(как в ролях и тарифах)
> 
> > В пользователя добавить поле tags (массив с тегами как в дискорде)(см. Дерево зависимостей). Так же организовать модуль с моделью тега и всеми запросами к нему. Зависимость many to many(т.е. много пользователей могут меть много тегов). Теги будут кастомные, поэтому сделай пока тестовые

Нет, изначально пустой массив, уровень доступа тоже не нужен. Ссылка в телеграме в группе CRM (https://t.me/+b9oeHCuWuyUzNmYy)
